### ISSUE TITLE
Incorrect readme

### ISSUE THREAD

**Issue by svrooij** [SierraSoftworks/tailscale-udm#32]
> **Can I route traffic from machines on my local network to Tailscale endpoints automatically?**
> Currently we are not aware of any supported means of achieving this. Tailscale's subnet routing is intended for Tailscale-to-subnet connections and doesn't provide explicit support for subnet-to-Tailscale connections.

![image](https://user-images.githubusercontent.com/1292510/203173305-52287a0d-206f-44b9-b70b-da3c0bef9eb7.png)

Each device automatically gets a routable (over Tailscale) IP. So my guess is that if you have a device in your local network and you want to connect to a device on the tailscale network, this packet will reach your UDM, and the UDM (connected to Tailscale) will know the route to this `100.64.0.0/10` network, which won't be reachable over the regular internet. Because they use this specific range, this route can easily be added to the UDM routing table (if that did not happen automatically when you connected to the tailscale network).

See [this page](https://tailscale.com/kb/1015/100.x-addresses/) for details.

**Comment by notheotherben** [comment]
In theory, yes - however because we're using user space networking for the Tailscale agent, it is not currently (to the best of my knowledge and based on the testing I've done) possible to configure a functional network route to Tailscale from your UDM.

If you're able to get this working, please let me know how and I'll ensure we have that updated in the README.
