### ISSUE TITLE
tailscale missing after firware upgrade

### ISSUE THREAD

**Issue by bennettp123** [SierraSoftworks/tailscale-udm#38]
Hi there,

My device just auto-updated (yes I have automatic updates enabled, yolo) from 2.4.23 to 2.4.26. Afterwards, tailscale was not installed.

Is this supposed to persist across firmware updates?

Edit: working fine after a reinstall 🤷🏻

**Comment by bennettp123** [comment]
I suspect this is not implemented. Unifi firmware upgrades typically only retain the contents of `/data` (uniOS 2.x) or `/mnt/data` (uniOS 1.x), as well as any packages installed.

I can think of two things that need to be fixed to get tailscale to persist across firmware updates:
* reinstall the tailscale package—I thought the upgrade process reinstalled deb packages automatically (I think that's how it works in [unifios-utilities](https://github.com/unifi-utilities/unifios-utilities)), so not sure what went wrong here—perhaps it was skipped (or failed) because it was installed using dpkg instead of apt-get?
* retain tailscale state after firmware update (`/var/lib/tailscale`, possibly more)

For reinstalling the package, we could probably just add that to the on_boot script

For the tailscale state, we could just replace it with a symlink to a folder in `/data` or `/mnt/data`

**Comment by notheotherben** [comment]
Thanks @bennettp123, I've not yet had the chance to test this on a UniFi OS 2.x device myself, so these details are extremely helpful.

I'll see what we can put together for those issues and let you know. One of the options around state is to configure the state directory using a flag when we start `tailscaled`, so that may also be a good option.

**Comment by notheotherben** [comment]
Just a heads up that I've added #41 with the hope that it'll ensure Tailscale is installed automatically after the OS is updated (it ensures that the correct apt source is present and we use that for installs).

I'll look at putting together something for the state directory as well (probably editing `/etc/default/tailscaled` to tell it to use `/data/tailscale` for state.

**Comment by notheotherben** [comment]
Okay, I've published `v2.3.2` which should address most of these issues, however I've not yet had the chance to test it against a real firmware upgrade (I've not received one since my UDM recently got updated to 2.x).

I'm hoping that the switch to using `apt` to install Tailscale should ensure it is re-installed after a firmware upgrade, however the `/etc/default/tailscaled` file might not include the required changes, in which case running `/data/tailscale/manage.sh install` should set things up correctly (and continue to use your original state file).

**Comment by GlitchWitch** [comment]
We had our tailscale instance on our UDM go missing as well. However the upgrade was from `1.12.33` to `1.12.38`. Running the [latest install script](https://github.com/SierraSoftworks/tailscale-udm/releases/tag/v2.3.3) seems to have solved it.

**Comment by notheotherben** [comment]
Thanks, I'm surprised that the 1.12.33 &rarr; 1.12.38 update resulted in it being removed as 1.x upgrades traditionally retained the contents of the `/mnt/data` partition. The upgrade from 1.x to 2.x is expected to wipe all content on the device, so that's normal - and I'll be keeping a close eye on 2.x to 2.x updates to see if they work correctly.

**Comment by mhubig** [comment]
Automatic UDM Pro update from version 1.12.38 to 2.5.17 wiped the Tailscale installation. Reinstalling with `curl -sSLq https://raw.github.com/SierraSoftworks/tailscale-udm/main/install.sh | sh` immediately fixed the issue.

**Comment by GlitchWitch** [comment]
Just had our UDM Pro upgrade from `2.4.27` to `2.5.17`, Tailscale did not stick around with it and the UDM has shown offline in the tailscale machine's list since the upgrade completed.

When we SSH in, it seems tailscale is no longer installed. Is there any extra data we can provide to help with troubleshooting @notheotherben

**Comment by notheotherben** [comment]
Thanks @GlitchWitch, I've put together #54 with the goal of solving the persistence issues (and implementing the auto-update functionality). That's going to require some testing (with a firmware upgrade on an eligible device). I've included testing steps in #54 and I'll look to get that PR merged once I (or someone else) has had a chance to confirm that it works correctly.

**Comment by notheotherben** [comment]
Okay folks, I've got #54 tested and working on my local UDM, I'll get that packaged up and a new release out shortly.

**Comment by notheotherben** [comment]
...and you'll find the release notes for [v2.4.0 here](https://github.com/SierraSoftworks/tailscale-udm/releases/tag/v2.4.0).

Please let me know if you run into any issues at all with it.
